import "./globals.css";
import Image from "next/image";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="h-14 mx-auto bg-[#00644b] overflow-hidden items-center">
          <div className="max-w-3xl mx-auto flex justify-between">
            <Image
              src="/../public/images/new-logo.webp"
              width={150}
              height={150}
              alt="logo"
            />
            <Image
              src="/../public/images/HPS-corelogo-a.webp"
              width={150}
              height={150}
              alt="title"
            />
          </div>
        </div>
        <div className="bg-amber-200 h-10 text-center py-2 text-[#00644b] font-bold">
          This is a full-width div with a yellow background color and centered
          text.
        </div>

        <nav className=" flex items-center justify-between flex-wrap bg-[#00644b] py-6 px-80">
          <div className="flex items-center flex-shrink-0 text-white">
            <Link legacyBehavior href="/product">
              <a>
                <Image
                  src="/../public/images/HPS-corelogo-a.webp"
                  width={200}
                  height={200}
                  alt="Logo"
                  className="h-8 w-auto"
                />
              </a>
            </Link>
          </div>
          <div className="block flex-grow lg:flex lg:items-center lg:w-auto pl-10">
            <div className="text-sm lg:flex-grow pr-10">
              <form>
                <input
                  className="w-full bg-white appearance-none border-2 rounded py-2 px-4 text-white leading-tight focus:outline-none focus:bg-white focus:border-purple-500"
                  type="text"
                  placeholder="What are you looking for?"
                />
              </form>
            </div>
            <div>
              <Link legacyBehavior href="/cart">
                <a className="inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-gray-900 hover:bg-white mt-4 lg:mt-0">
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">
                    <path d="M0 24C0 10.7 10.7 0 24 0H69.5c22 0 41.5 12.8 50.6 32h411c26.3 0 45.5 25 38.6 50.4l-41 152.3c-8.5 31.4-37 53.3-69.5 53.3H170.7l5.4 28.5c2.2 11.3 12.1 19.5 23.6 19.5H488c13.3 0 24 10.7 24 24s-10.7 24-24 24H199.7c-34.6 0-64.3-24.6-70.7-58.5L77.4 54.5c-.7-3.8-4-6.5-7.9-6.5H24C10.7 48 0 37.3 0 24zM128 464a48 48 0 1 1 96 0 48 48 0 1 1 -96 0zm336-48a48 48 0 1 1 0 96 48 48 0 1 1 0-96z" />
                  </svg>
                </a>
              </Link>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
