import "./globals.css";
// Components
import Header from "./components/Layout/Header";
import Footer from "./components/Layout/Footer";
//Image

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
